version: '3.7'
services:
  rest-api:
    container_name: 'CONTAINER NAME HERE'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./

  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: 'CADDY CONTAINER NAME HERE'
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
