import { type NextPage } from 'next';
import Head from 'next/head';
import { signIn } from 'next-auth/react';
import { Timeline } from '~/components/Timeline';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <button onClick={() => signIn()}>Login</button>

        <Timeline where={undefined} />
      </div>
    </>
  );
};

export default Home;
